// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gzbtsmxdgtwyjvkecsft.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imd6YnRzbXhkZ3R3eWp2a2Vjc2Z0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzU4NDY5ODgsImV4cCI6MjA5MTQyMjk4OH0.9yWaJcW5o-plb41_9EvHuc7NNyUhzGDhyKU876SgsI8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});